function get_eMailParser(a){zzz=a;var b=new parseEmail(a);b.parseMail(b.message);var c=b.message;if(c.mimeFragments.length)for(var e=0;e<c.mimeFragments.length;e++)a=c.mimeFragments[e],c.mimeFragments[e]={},c.mimeFragments[e].eMailParser=get_eMailParser(a),a=c.mimeFragments[e].eMailParser.message,a.content_TEXT&&a.contentType_TEXT&&a.contentType_TEXT.toLowerCase().indexOf("text/plain")+1&&!c.content_TEXT&&(c.content_TEXT=a.content_TEXT,c.contentType_TEXT=a.contentType_TEXT),a.content_HTML&&a.contentType_HTML&&
a.contentType_HTML.toLowerCase().indexOf("text/html")+1&&!c.content_HTML&&(c.content_HTML=a.content_HTML,c.contentType_HTML=a.contentType_HTML);return b}function parseEmail(a){this.message=new emailDocument;this.message.loadFile(a)}
parseEmail.prototype.splitDoc=function(a){var b=[];var c=a.search(utility.regexes.doubleNewLine);b[0]=a.substring(0,c);b[0]=b[0].replace(utility.regexes.fold," ").trim();b[1]=a.substring(c);b[1]=b[1].split("\n");b[1].shift();b[1].shift();b[1]=b[1].join("\n");return{header:b[0],body:b[1]}};
parseEmail.prototype.parseHeader=function(a){var b={};if(""===a)return b;a.split(utility.regexes.newLine).forEach(function(c){c=c.split(utility.regexes.headerAttribute);if(""===c[0]||"undefined"===typeof c[0])return!0;c[0]=c[0]||"";c[1]=c[1]||"";b[c[0].trim().toLowerCase()]=c[1].trim()});this.storeHeader(b)};
parseEmail.prototype.parseBody=function(a){var b={};if(""===a)return b;b=(this.message.headers["content-transfer-encoding"]||"").toLowerCase().trim();"base64"===b?a=utility.decodeBase64(a):"quoted-printable"===b&&(a=utility.decodeQuotedPrintable(a.replace(/\n\.\./g,"\n.")));b=(this.message.headers["content-type"]||"").toLowerCase().trim().split(/\//);switch(b[0]){case "multipart":this.parseMultiPart(a);break;case "text":b[1].toLowerCase().split("charset=")[1].indexOf("utf-8")+1&&(a=decodeToUTF8(a));
this.parseTextBody(a);break;default:this.parseTextBody(a)}};function decodeToUTF8(a){try{return decodeURIComponent(escape(a))}catch(c){var b=a.length;return 1<b?(b=parseInt(b/2),decodeToUTF8(a.substr(0,b))+decodeToUTF8(a.substr(b))):a}}function decodeBASE64(a){try{return atob(a)}catch(c){var b=a.length;return 1<b?(b=parseInt(b/2),decodeBASE64(a.substr(0,b))+decodeBASE64(a.substr(b))):a}}parseEmail.prototype.parseTextBody=function(a){this.storeBody(a)};
parseEmail.prototype.parseMultiPart=function(a){var b=utility.getIndicesOf(this.message.boundaries,a);for(i=0;i<b.length-1;i++){var c=a.substring(b[0+i]+this.message.boundaries.length,b[1+i]);this.message.mimeFragments.push(c)}};parseEmail.prototype.storeBody=function(a){this.message.contentType_HTML&&(this.message.content_HTML=a);this.message.contentType_TEXT&&(this.message.content_TEXT=a)};
parseEmail.prototype.storeHeader=function(a){this.message.headers=a;a=this.message.headers["delivered-to"]||this.message.headers.to;var b=this.message.headers["return-path"]||this.message.headers.from,c=this.message.headers.subject||"",e=this.message.headers["x-originating-ip"]||"",d=this.message.headers["content-type"]||"text/plain",f=d.split("boundary=");2>f.length&&(f=d.split("BOUNDARY="));1<f.length&&(this.message.boundaries="--"+f[1].replace(/"/g,"").split(";")[0]);this.message.to=utility.extractEmail(a);
this.message.from=utility.extractEmail(b);this.message.subject=utility.extractEncode_word(c);this.message.originatingIp=utility.extractIP(e);d.toLowerCase().indexOf("text/html")+1&&(this.message.contentType_HTML=d);d.toLowerCase().indexOf("text/plain")+1&&(this.message.contentType_TEXT=d)};parseEmail.prototype.parseMimeFragment=function(a){};parseEmail.prototype.parseMail=function(a){a=this.splitDoc(a.raw);this.parseHeader(a.header);this.parseBody(a.body)};
var utility={regexes:{newLine:/\r?\n/,doubleNewLine:/\r?\n\r?\n/,headerAttribute:/:(.+)?/,fold:/\r?\n(?:[ \t]+)/g,email:/(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/g,ipAddr:/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/,header:/^(.+): ((.|\r\n\s)+)\r\n/mg},extractEmail:function(a){a=(a||"").match(utility.regexes.email);return null===a?"":1<a.length?a:a[0]},extractIP:function(a){a=(a||"").match(utility.regexes.ipAddr);
return null===a?"":1<a.length?a:a[0]},extractEncode_word(a){a=(a||"").split("?");for(var b="",c="",e,d=0;d<a.length;d++)if("="==(a[d+0]||"").substr((a[d+0]||"").length-1,1)&&"="==(a[d+4]||"").substr(0,1)){a[d+0]=a[d+0].substr(0,a[d+0].length-1);a[d+4]=a[d+4].substr(1);" ="==a[d+4]&&(a[d+4]=a[d+4].substr(1));c=a[d+1];encoding=a[d+2];e=a[d+3];switch(encoding.toUpperCase()){case "B":e=utility.decodeBase64(e);break;case "Q":e=utility.decodeQuotedPrintable(e.split("_").join(" "))}b+=a[d+0]+e;d+=3}else b+=
a[d+0],d+1<a.length&&(b+="?");"UTF-8"==c.toUpperCase()&&(b=decodeToUTF8(b));return b},decodeBase64:function(a){return decodeBASE64(a.trim()).toString()},decodeQuotedPrintable:function(a){return a.replace(/=\r?\n/gm,"").replace(/=([0-9A-F]{2})/gim,function(b,c){return String.fromCharCode(parseInt(c,16))})},getIndicesOf:function(a,b){var c=0,e=(a||"").length,d=[];for(-1==b.indexOf(a+"--")&&(b+=0+a+"--");-1<(c=b.indexOf(a,c));)d.push(c),c+=e;return d}};
function emailDocument(){this.headers={};this.raw;this.mimeFragments=[];this.headerBlock;this.bodyBlock;this.originatingIp;this.replyTo;this.contentType_TEXT;this.contentType_HTML;this.boundaries;this.from;this.to;this.subject;this.content_TEXT;this.content_HTML;this.html;this.attachments}emailDocument.prototype.loadFile=function(a){this.raw=a.toString()};
