var app_UI="JQM",YPOS=0,CurrentPageLoad="";
function onLoad_CONTINUE(){document.addEventListener("scroll",function(b){setTimeout(function(){CurrentPage[0].id==$("body").pagecontainer("getActivePage")[0].id&&0==YPOS?CurrentPage.data("YPOS",window.scrollY):(clearTimeout(YPOS),YPOS=setTimeout(function(){YPOS=0},1E3))},500)});$("body").on({pagecontainerchange:onLoad_JQM});$(window).on({pagecontainerbeforechange:function(b,c){return sii_pagecontainerbeforechange(b,c)}});var a=document.getElementsByTagName("body")[0];$(a).is(":visible")&&(a.style.display=
"none",a.style.visibility="",$("#body_main").fadeIn(1E3));onLoad_JQM()}
function onLoad_JQM(){CheckLeaseTime_OK();back_CurrentPage=CurrentPage;CurrentPage=$("body").pagecontainer("getActivePage");if(CurrentPage[0].id!=CurrentPageLoad){CurrentPageLoad=CurrentPage[0].id;$("[data-role='navbar'] [type=button]").on({focus:function(b,c){this.classList.add("ui-btn-active")},blur:function(b,c){this.classList.remove("ui-btn-active")}});$.mobile.silentScroll(CurrentPage.data("YPOS"));myForm=wd=CurrentPage.find("form[name^=myForm]")[0]||CurrentPage.find("form")[0]||CurrentPage[0];
-1==(back_CurrentPage[0].id+CurrentPage[0].id+"").indexOf("-dialog")&&(saveItemFocus=0);NameItemFocus="";DBF_null_key=null;DBF_query_key="key";DBF_connect_key=null;DBF_insert_key=!0;DBF_name_key="Documento";DBF_action=myForm?myForm.action:null;try{My_onLoad()}catch(b){console.error(b)}page_My_OnLoad=CurrentPage.attr("id").split("^").join("").split(".").join("_")+"_My_onLoad";try{if("function"==typeof eval(page_My_OnLoad))try{onLoad_JQM_CONTINUE()}catch(b){console.error(b)}}catch(b){var a=sii_path_htm_name.split("/");
a[a.length-1]="";a=a.join("/");a=".."+a+CurrentPage.attr("id")+".js?"+sii_version;$.ajax({url:a,dataType:"script",cache:!0}).always(function(c,d,e){try{onLoad_JQM_CONTINUE()}catch(g){console.error(g)}})}}}
function onLoad_JQM_CONTINUE(){try{eval(page_My_OnLoad+"()")}catch(b){console.error(page_My_OnLoad,b)}$("[data-type=search]").not("[readonly], [data-ext=false]").each(function(b,c){c.addEventListener("focus",function(d){$(this).trigger("keypress")})});$("[data-type=search][data-F2]").not("[readonly], [data-ext=false]").each(function(b,c){b=c.closest("div");var d=document.createElement("a");d.style.position="absolute";d.style.top="00px";d.style.width="20px";d.style.height="31px";d.style.zIndex=1;d.title=
"haz clic para realizar busquedas avanzadas";d.addEventListener("click",function(e){eval(c.dataset.f2)});b.append(d)});try{CurrentPage.find("[data-role=navbar]").navbar("refresh")}catch(b){}try{CurrentPage.find("[data-role=header],[data-role=footer]").toolbar({tapToggle:!1,hideDuringFocus:"",refresh:!0})}catch(b){}var a=CurrentPage.find(".subPag:visible").first();a.length||(a=CurrentPage.find(".subPag:first"));if(a.length){CurrentPage.find(".subPag").not(a).hide();try{eval(a.attr("id").split("^").join("").split(".").join("_")+
"_My_onLoad()")}catch(b){}}!DBF_connect_key&&wd&&(wd.codigo?DBF_connect_key=wd.codigo:wd.elements&&(DBF_connect_key=wd.elements[0]));DBF_connect_key&&!DBF_connect_key.initValue&&(DBF_connect_key.initValue=DBF_connect_key.value);if(!NameItemFocus)try{INPUT=inputList(),NameItemFocus=INPUT[saveItemFocus].name}catch(b){try{NameItemFocus=INPUT[0].name}catch(c){}}navigator.userAgent.toUpperCase().indexOf("ANDROID")+1||NameItemFocus&&InitInput(NameItemFocus);serializeForm();try{$(".image").popImg()}catch(b){}autocomplete=
document.querySelectorAll("[autocomplete=off]");if(autocomplete.tagName=autocomplete.length)autocomplete=autocomplete[0].querySelectorAll("input");autocomplete.length&&(a=document.getElementById("autocomplete")||{},"autocomplete"==a.name&&(a.addEventListener("change",setAutocomplete),a.checked="true"===localStorage.getItem("autocomplete")),setAutocomplete(a));setTimeout(function(){UpdateForm=!0},500);input_list();try{$('input[type="checkbox"][data-disabled]').prop("disabled",!0).checkboxradio("refresh")}catch(b){}$("[data-role=header] h1").css("cursor",
"pointer").click(function(){jQuery_confirm(sii_cia_name,"       <table>        <tr>         <td>Compa&#241;ia</td><td>"+sii_cia_code+"</td></tr>        <tr>         <td>Operador</td><td>"+sii_login+"</td></tr>        <tr>         <td>Usuario</td><td>"+sii_fid0+"</td></tr>        <tr>         <td>Perfil</td><td>"+sii_oper+"</td></tr>       </table>         ")});CurrentPage[0].dataset.toggleMenu||(CurrentPage[0].dataset.toggleMenu=!0,CurrentPage.find("*[class^=toggle-]").hide(),a=CurrentPage.find("[data-toggle]"),
a.find("a").addClass("ui-icon-plus").removeClass("ui-icon-carat-r").css("backgroundColor","#ededed"),a.on("click",function(){var b=this.querySelectorAll("a")[0].classList.contains("ui-icon-plus");CurrentPage.find("*[class^=toggle-]").hide();CurrentPage.find("[data-toggle]").find("a").addClass("ui-icon-plus").removeClass("ui-icon-minus");b&&(CurrentPage.find(".toggle-"+this.dataset.toggle).show(),CurrentPage.find("[data-toggle="+this.dataset.toggle+"]").find("a").addClass("ui-icon-minus").removeClass("ui-icon-plus"));
$(this).closest("div[data-role=panel]").trigger("create")}),a=CurrentPage.find("[data-toggle].defaultToggle"),a.length||(a=CurrentPage.find("[data-toggle]:first")),a.click(),a.closest("div[data-role=panel]").trigger("create"))}function My_submit(a,b){try{return eval(CurrentPage[0].id.replace(/(\.)/g,"_")+"_My_submit(button, preview)")}catch(c){return!0}}
function jQuery_confirm(a,b,c,d,e,g,h){a=a||"Alerta!";e=e||"jQuery_confirm_Frame"+(new Date).getTime();c=c||[{text:"Continua",click:function(){jQframeObj[e].popup("close")}}];d=d||"delete-red";g=g||!0;h=h||"";"none"==c&&(c="");1==g?(data_icon='data-icon="'+d+'"',data_ancor=""):(data_icon='data-icon="false"',data_ancor="_not");html='<div data-role="popup" id="'+e+'" data-theme="a" data-overlay-theme="b" style="max-width:600px;" data-dismissible="'+g+'">';html+=' <ul data-role="listview"><li '+data_icon+
' data-theme="b" style="margin: -1px -1px -1px -1px;"><a'+data_ancor+' href="#" data-rel="back">'+a+"</a></li></ul>";html+=' <div data-role="main" class="ui-content">';html+="  <h3><center>"+b+"</center></h3>";if(c){1<c.length&&(html+='<fieldset class="ui-grid-'+String.fromCharCode(95+c.length)+'">');for(i=0;i<c.length;i++)1<c.length&&(html+='<div class="ui-block-'+String.fromCharCode(97+i)+'">'),html+='<input type="button" data-mini="true" data-theme="b" id="'+HTA(c[i].text)+'" name="'+HTA(c[i].text)+
'" value="'+c[i].text+'">',1<c.length&&(html+="</div>");1<c.length&&(html+="</fieldset>")}html+=" </div>";html+="</div>";jQframeObj[e]=$(html).popup({afterclose:function(k){if(h)try{h(k)}catch(l){console.error(l)}k.stopPropagation();windowFocus.splice(windowFocus.indexOf(frame_name));try{$(this).popup("destroy")}catch(l){}},history:!0,positionTo:"window",transition:"pop"}).trigger("create").popup("open");if(c)for(i=0;i<c.length;i++)jQframeObj[e].find("#"+HTA(c[i].text)).on("click",c[i].click),i||
jQframeObj[e].find("#"+HTA(c[i].text))[0].focus();UpdateForm=!1;windowFocus.push(e);return jQframeObj[e]}function photoCamera(a,b){CallSQL("/sinfonix/html/camera.htm","list","",a,b," ^HTML.www ",320,240,"WebCam","","",function(){jQframeObj[this.id].popup("destroy");jQframeObj[this.id]=""})}
function CallSQL(a,b,c,d,e,g,h,k,l,n,p,m,f){jQframeObj.checkCredentials&&""!=jQframeObj.checkCredentials&&"^LOGIN.www"!=a||(d=d?d.split("undefined").join(""):"",e=e?e.split("undefined").join(""):"",c=(c=c?c.split("undefined").join(""):"")?b+'="'+c+'"':b,qstr=escape(a.split(" ")[0]+" "+c+" "+d+" "+e),f=f||(a+b+d).toUpperCase(),g=g||" ",l=l||"("+a+d+")",n=n||"delete",m=m||"",1==(p||!0)?(data_icon='data-icon="'+n+'"',data_ancor=""):(data_icon='data-icon="false"',data_ancor="_not"),"list"==b?(jQframeObj[f]?
jQframeObj[f].popup("open"):(h=h||635,k=k||405,html='<div data-role="popup" id="'+f+'" data-theme="a" data-overlay-theme="b" style="border: 0px; width:'+(4+h)+"px; height:"+(47+k)+'px; overflow: hidden; max-width:600px;">',html+='<ul data-role="listview"><li '+data_icon+' data-theme="b" style="margin: -1px -1px -1px -1px;"><a'+data_ancor+' href="#" data-rel="back">'+l+"</a"+data_ancor+"></li></ul>",html+='<div data-role="main" class="ui-content">',html+='<iframe name="'+f+'" style="border: 0px; width:'+
h+"px; height:"+k+"px; overflow: hidden; position:relative; top:-14px; left:-14px;",html+='" src="/cgi-bin/sinfonix_ngz.pl?'+sii_system+g+qstr+'"></div>',jQframeObj[f]=$(html).popup({history:!0,afterclose:function(q){q.stopPropagation();windowFocus.splice(windowFocus.indexOf(f));if("function"==typeof m)try{m()}catch(r){console.error(m,r)}}}).trigger("create").popup("open",{positionTo:"window",transition:"pop"})),windowFocus.push(f)):jQframeObj[f]=$('<iframe id="'+f+' name="'+f+'" title="('+a+d+')" src="/cgi-bin/sinfonix.pl?'+
sii_system+g+qstr+'">').css("display","none").appendTo("body"))}function showPag(a,b){var c="",d=$(document.getElementById(a.split("#").join(""))),e=$(".subPag:visible");b&&e.attr("id")>d.attr("id")&&(c="reverse");d.length&&e.attr("id")!=d.attr("id")&&(e.length?(e.removeClass("slide in reverse").addClass("slide out "+c),setTimeout(function(){e.removeClass("slide out "+c).css("display","none");setTimeout(function(){showPag_CALLBACK(d,"slide",c)},50)},125)):showPag_CALLBACK(d,"slide",c))}
function showPag_CALLBACK(a,b,c){a.addClass(b+" in  "+c).css("display","");try{eval(a.attr("id").split("^").join("").split(".").join("_")+"_My_onLoad()")}catch(d){}setTimeout(function(){NameItemFocus=inputList()[0].name;navigator.userAgent.toUpperCase().indexOf("ANDROID")+1||InitInput(NameItemFocus)},400)}
function refreshPage(a,b){a=a||window.location.href;b="object"==typeof b?b:{};void 0==b.changeHash&&(b.changeHash=!1);void 0==b.reload&&(b.reload=!0);void 0==b.showLoadMsg&&(b.showLoadMsg=!1);void 0==b.transition&&(b.transition="none");void 0==b.allowSamePageTransition&&(b.allowSamePageTransition=!0);if(a!=window.location.href)try{var c="";0!=a.indexOf("http")&&0!=a.indexOf(".")&&0!=a.indexOf("/")&&(c=$("#"+a+"[data-role]"));if(c.length)a=c;else throw"pagina no esta en el DOM, intenta cargarla desde la WEB";
}catch(d){console.error(d);if(0==b.changeHash)return!1;0!=a.indexOf("http")&&0!=a.indexOf(".")&&0!=a.indexOf("/")&&(a=unescape(unescape(window.location.href)).split(" ")[0]+" "+a)}setTimeout(function(){$.mobile.pageContainer.pagecontainer("change",a,b)},500);return!0}
function sii_pagecontainerbeforechange(a,b){clearTimeout(YPOS);YPOS=setTimeout(function(){YPOS=0},1E3);if("string"==typeof b.toPage)if(disable_pagecontainerbeforechange)setTimeout(function(){disable_pagecontainerbeforechange=!1},500);else if(void 0==b.options.direction){if(b.toPage.indexOf("-listbox")+1||b.toPage.indexOf("-dialog")+1)UpdateForm=!1}else if(UpdateForm){if(historyButton=!0,!KEYS_18_78())return UpdateForm=!1,bak_originalForm=originalForm,window.parent.setTimeout(function(){UpdateForm=
!0},500),window.parent.setTimeout(function(){originalForm=bak_originalForm},500),"back"==b.options.direction?history.forward():history.back(),!1}else setTimeout(function(){UpdateForm=!0},500)};
