var sii_name="Sinfonix 2000 for WEB",wd=document,myForm=wd,saveItemFocus=0,NameItemFocus="",DBF_null_key=null,DBF_query_key="key",DBF_connect_key=null,DBF_insert_key=!0,DBF_name_key="Documento",DBF_action=myForm?myForm.action:null,WScreen_W=1024<window.innerWidth?1024:window.innerWidth,WScreen_H=768<window.innerHeight?768:window.innerHeight,WScreen_C=window.screen.colorDepth,saveKeydown="",MenuItem=0,Menu_PREFIX="LN_",Menu_PROCESO="",OSTOut=0,trash=null,COLS=0,Old_Obj="",pgms_count=null,docment_itemMenuSelect=
null,e_pageX=0,e_pageY=0,jQframeObj=[],ItemBlurIsTrue=!0,EVENT="",CTRLKEY="",KEYS=[],INPUT=null,sii_search_cache={},originalForm=!1,UpdateForm=!1,disable_pagecontainerbeforechange=!1,historyButton=!1,$main="",CurrentPage=[{}],windowFocus=[],windowFocus_backup="",set_lockScreen="",frame_name="",tableRow="",tableRow_Light="",lineNum=26,CheckLeaseTimer=0,iconGeneric="/images/file-user.png",ESCAPE2=0,CLOSED=!0,ONBEFOREUNLOAD=!0;
function onLoad(){window_title=(document.querySelector("title")||{}).text||document.title||sii_name;window!=window.parent&&window.parent.window_title&&(window_title=window.parent.window_title+" / "+window_title);top.window.document.title=window_title;UpdateForm=!0;submit=submit_ext;onkeydown=onkeyup=keystroke;onfocus=function(){KEYS=[]};""==$main&&($main=$("#main").html());$(window).on({beforeunload:function(){if(ONBEFOREUNLOAD&&IfExistButton()&&(-1<myForm.name.indexOf("lock")&&(myForm.button.value=
myForm.button.defaultValue="Nuevo",myForm.preview&&(myForm.preview.value=myForm.preview.defaultValue="OFF"),ONBEFOREUNLOAD=!1,myForm.submit()),!verifidForm()))return!0},mousedown:function(){select_activeElement()},keydown:function(){select_activeElement()}});$("*[class^='onLD']").on({focus:function(){JS(this,"focus","onLD")},blur:function(){blurElement=this;setTimeout("JS('','focus','onLD')",100)}});navigator.serviceWorker&&(navigator.serviceWorker.onmessage=a=>{a=a.data;switch(a.action){case "eval":eval(a.value);
break;default:a.value&&navigator.serviceWorker.controller.postMessage({action:"message",value:a.value})}},navigator.serviceWorker.register("../SW.js").then(function(a){return a.pushManager.getSubscription().then(async function(b){if(b)return b;b=await (await fetch("/cgi-bin/sinfonix_sql.pl?^SW.www GetPublicKey")).text();b=urlBase64ToUint8Array(b);return a.pushManager.subscribe({userVisibleOnly:!0,applicationServerKey:b})})}).then(function(a){a=JSON.stringify(a);var b=Cookies("Read","pushMsg")||"";
Cookies("Write","pushMsg",a,3650);a=setForm("subscription",a);a+=setForm("bak_subscrip",b);fetch("/cgi-bin/sinfonix_sql.pl?^SW.www Register",{method:"post",headers:{"Content-type":"application/x-www-form-urlencode","Content-length":a.length},body:a}).then(function(){try{GeoLocation()}catch(c){console.error(c)}})}).catch(function(){}));if(window!=window.parent&&window.parent.focusWhenReady)try{window.parent.focusWhenReady()}catch(a){console.error(a)}onLoad_CONTINUE()}
function keystroke(a){EVENT=a||event;saveKeydown=document.all?EVENT.keyCode:EVENT.which;a=KEYS.indexOf(saveKeydown);if("keydown"==EVENT.type){-1==a&&KEYS.push(saveKeydown);try{if("13"==KEYS||CheckLeaseTime_EXPIRATION()){var b="KEYS_"+KEYS.sort().join("_"),c="My_"+b;"JQM"==app_UI&&(c=CurrentPage[0].id.split(".").join("_")+"_"+c);27==saveKeydown&&KEYS.splice(a,1);return fn_KEYS(c)?fn_KEYS(b):void 0}}catch(d){}}else if(EVENT="",a+1)for(;a=KEYS.indexOf(saveKeydown)+1;)KEYS.splice(a-1,1);else KEYS=[]}
function fn_KEYS(a){try{if("function"==typeof eval(a))return 1<KEYS.length&&(EVENT.stopPropagation(),EVENT.preventDefault()),eval(a+"()")}catch(b){}return!0}
function KEYS_13(a){a=a||1;var b=EVENT.target;if(b.getAttribute("contenteditable"))return!0;EVENT.stopPropagation();"A"==b.tagName&&EVENT.preventDefault();INPUT="";if(!b.name){var c=b.id.split("-");c=b.id&&!b.id.indexOf("select")?b.nextElementSibling:1<c.length?document.getElementById(c[0]):"";c||(INPUT=inputList(),c=INPUT[saveItemFocus||INPUT.length-1]);b=c}INPUT=INPUT||inputList();if("TEXTAREA"==b.tagName||"true"==b.getAttribute("contenteditable")){c=b.selectionStart;var d=b.selectionEnd,f=b.value.length}else c=
d=f=0;if(0==c&&d==f){for(c=0;c<INPUT.length&&b!=INPUT[c];)c++;c==INPUT.length&&(c=saveItemFocus?saveItemFocus:-1==a?0:c--);ItemFocus(ItemBlur(c,a));return!1}}function KEYS_13_16(){return KEYS_13(-1)}function KEYS_27(a){"close"!=a&&closeWindow(window,a)||("close"==a||ESCAPE2?closeWindow(window.parent,a)||("close"==a||top.window.CLOSED)&&top.window.close():(ESCAPE2=1,setTimeout(function(){ESCAPE2=0},500),KEYS_18_78()));return!1}function KEYS_18_78(){return writeDocument("Nuevo","OFF")}
function KEYS_18_71(){return writeDocument("Acepta","OFF")}function KEYS_18_69(){return writeDocument("Elimina","OFF")}function KEYS_18_68(){return verifidForm("myForm.reset()")}function KEYS_18_80(){return writeDocument("Acepta","ON")}function KEYS_17_80(){return writeDocument("Acepta","PRINT")}function KEYS_18_77(){send_eMail();return!1}
function writeDocument(a,b){var c="My_writeDocument";"JQM"==app_UI&&(c=CurrentPage.attr("id").split("^").join("").split(".").join("_")+"_"+c);try{if("function"==typeof eval(c)&&!eval(c+"(button, preview)"))return!1}catch(d){}return writeDocument_continue(a,b)}function writeDocument_continue(a,b){return jQframeObj[frame_name]&&""!=jQframeObj[frame_name]?!1:""==b||"OFF"==b||myForm&&myForm.preview?submit_ext(a,b):print()}
function closeWindow(a,b){var c=a.windowFocus.length;if("popImg"==a.windowFocus[c-1])return!0;if("JQU"==a.app_UI){if(c)try{return a.jQframeObj[a.windowFocus[c-1]].dialog("close"),!0}catch(d){try{return a.jQframeObj[a.windowFocus[c-1]].close(),!0}catch(f){try{return metroDialog.close(a.jQframeObj[a.windowFocus[c-1]][0].closest("[data-role=dialog]")),!0}catch(h){}}}}else{if("close"!=b&&CurrentPage[0].querySelector("div[data-role=header]").classList.contains("ui-panel-page-content-open"))return!0;if(c&&
(a=unescape(unescape(location.href)),2<a.split(" ").length||1<a.split("#").length))return verifidForm("history.back();")}return!1}function KEYS_32(){var a="undefined"==typeof window.event?EVENT.srcElement:EVENT.target;"A"!=a.tagName&&"BUTTON"!=a.tagName&&"SELECT"!=a.tagName||a.click();KEYS=[]}
function KEYS_113(){var a="undefined"!=typeof window.event?EVENT.srcElement:EVENT.target;if(a=a.getAttribute("data-F2")||a.onchange||a.href){a+="";z=a.indexOf("{\n");z+1&&(a=a.substr(z+2));z=a.indexOf("\n}");z+1&&(a=a.substr(0,z));z=a.toLowerCase().indexOf("javascript:");z+1&&(a=a.substr(z+11));y="'record'";z=a.toLowerCase().indexOf(y);z+1||(y="'lock'",z=a.toLowerCase().indexOf(y));z+1&&(a=a.split(a.substr(z,y.length)).join("'list'"));try{eval(a)}catch(b){console.error(b,a)}}}
function KEYS_116(){EVENT.preventDefault();1<location.href.split("#").length?KEYS_27():location.reload(!0)}function InitInput(a){var b=0;INPUT=inputList();if(a)for(;b<INPUT.length&&INPUT[b].name!=a;)b++;b==INPUT.length&&(b=0);return ItemFocus(ItemSelect(b,1))}function ItemSelect(a,b,c){for(;-1<a&&a<INPUT.length&&(INPUT[a].disabled||!isVisible(INPUT[a]));)a+=b;return c?a:-1<a?a<INPUT.length?a:ItemSelect(0,1,!0):ItemSelect(INPUT.length-1,-1,!0)}
function isVisible(a){try{return $(a).is(":visible")&&"visible"==$(a).css("visibility")}catch(b){return!1}}
function ItemFocus(a){INPUT=INPUT||inputList();if(0>a||a>=INPUT.length)return-1;try{INPUT[a].tagName.indexOf("H")?INPUT[a].focus():INPUT[a].querySelector("a").focus(),saveItemFocus=a}catch(c){try{INPUT[saveItemFocus].focus()}catch(d){try{INPUT[0].focus(),saveItemFocus=0}catch(f){return console.error(f,INPUT[a]),-1}}}a=INPUT[saveItemFocus];var b=a.type;"button"!=b&&"submit"!=b&&"reset"!=b&&a.select&&a.select();return saveItemFocus}
function ItemBlur(a,b){INPUT=INPUT||inputList();try{INPUT[a].value=INPUT[a].value,INPUT[a].blur()}catch(c){console.error(c)}return ItemSelect(a+b,b)}function inputList(a){a=$(document.querySelector(".ui-popup-active"));a=a.length?a.find("form[name^=myForm]")[0]||a.find("form")[0]||a[0]:windowFocus.length?jQframeObj[windowFocus[windowFocus.length-1]].parent():document;INPUT=$(a).find("[name]").not("form, img");0==INPUT.length&&(INPUT=$(a));return INPUT}
function CallPGM(a,b,c,d,f){var h=(c||"").toUpperCase().split("WIDTH=");d=1<h.length?h[1].split(",")[0]:"";h=(c||"").toUpperCase().split("HEIGHT=");c=1<h.length?h[1].split(",")[0]:"";WScreen_W=1024<window.innerWidth?1024:window.innerWidth;WScreen_H=768<window.innerHeight?768:window.innerHeight;if("JQM"==app_UI||"window"==f||EVENT&&(EVENT.shiftKey||EVENT.ctrlKey))""==d&&(d=WScreen_W-4,1020>d&&(d=1020)),""==c&&(c=WScreen_H-4,596>c&&(c=596)),b=b||(f||"window")+(new Date).getTime(),c="resizable,scrollbars,top="+
(screen.width-d)/2+",left="+(screen.height-c)/2+",width="+d+",height="+c,wl=window.open("/cgi-bin/sinfonix.pl?"+sii_system+"%20"+a,b,c),wl.focus();else{if(""==d||d>WScreen_W)d=WScreen_W;if(""==c||c>WScreen_H)c=WScreen_H;var g=document.createElement("iFrame"),l="iFrame"+HTA(a);g.style.visibility="hidden";g.style.position="fixed";g.style.overflow="hidden";g.style.zIndex="1000";g.style.left=(window.innerWidth-d)/2+"px";g.style.top=(window.innerHeight-c)/2+"px";g.style.width=d+"px";g.style.height=c+"px";
g.id=g.name=l;g.src="/cgi-bin/sinfonix_ngz.pl?"+sii_system+" "+a;g.dialog=function(k){win=window.frames[this.id];win.IfExistButton&&win.IfExistButton()&&win.submit_true("Nuevo","OFF");windowFocus.splice(windowFocus.indexOf(l));jQframeObj[l]="";g.parentNode.removeChild(g);top.window.document.title=window.window_title;lockScreen("unlock");InitInput(NameItemFocus)};g=document.body.appendChild(g);lockScreen("lock",1);jQframeObj[l]=g;windowFocus.push(l);focusWhenReady=function(){var k=document.getElementById(l);
k&&(k.style.animationName="openWin",k.style.animationDuration="1s",k.style.overflow="auto",k.style.visibility="",k.contentWindow.focus())}}}function callSQL_Date(a,b){b=b||"gre";a.indexOf(".head.document")||(a=a.substr(15));if(a.indexOf("(")+1){var c="gre"!=b?b:"{value:''}";b=a}else c=a,b=c+".value="+b;sqln="callSQL_Date_Frame_"+HTA(b+c)+a.indexOf("(")+1;b='date="'+eval(c).value+'" window.parent.'+b;CallSQL("^DATE.www","list","",b,"","",170,235,"Calendario","",sqln)}
function LoadRecord(a,b,c){if(!UpdateForm)return!1;UpdateForm=!1;lockScreen();b=b||"get";c=c||DBF_action;return verifidForm("LoadRecord_OK('"+eval(DBF_query_key)+"','"+b+"','"+c+"')")}function LoadRecord_OK(a,b,c){"JQU"==app_UI?("post"==b?$.post(c,a):$.get(c+encodeURIComponent(" "+a))).done(LoadRecord_done):location.href=c+encodeURIComponent(" "+a)}
function LoadRecord_done(a){UpdateForm=!0;lockScreen("unlock");var b=document.createElement("div"),c=document.getElementById("main");b.innerHTML=a;if(a=b.querySelector("#main"))c.innerHTML=a.innerHTML,document.oldTitle=document.title,document.title=b.querySelector("title").text;var d=b.querySelectorAll("script");d.length&&Object.keys(d).forEach(function(f){eval(d[f].innerHTML)});a?onLoad():alert(message.split("<BR>").join("\n")+"\n\n"+error.split("<BR>").join("\n"))}
function VerifidLoadRecord(a,b,c,d){d=d||a;if(null!=DBF_null_key)null_key=DBF_null_key;else{null_key="";try{if(!(d.length%2)&&"200".indexOf(d.substr(0,2))+1)for(b=0;b<d.length;b+=2)null_key+=d.substr(0,2)}catch(f){console.error(f)}}if(""!=d&&d!=null_key){try{DBF_connect_key.value=DBF_connect_key.initValue}catch(f){}return LoadRecord(a)}if(0==DBF_insert_key)return jQuery_confirm("Alerta!","El "+DBF_name_key+":"+DBF_connect_key.value+" NO Existe!!, Debe colocar un codigo valido","","","","",function(){DBF_connect_key.value=
DBF_connect_key.initValue;DBF_connect_key.focus();DBF_connect_key.select()}),!1}
function submit_ext(a,b){if(!UpdateForm||window.My_submit&&1!=My_submit(a,b))return!1;if(IfExistButton())switch(a){case "Elimina":var c="JQU"==app_UI?'$( this ).dialog("close")':"history.back()";jQuery_confirm("Cuidado!","Desea Eliminar el registro?",[{text:"Eliminar",click:function(){eval(c);submit_true(a,b)}},{text:"Cancelar",click:function(){eval(c)}}],"","DELETE_SUBMIT_BUTTON");return!1;case "Nuevo":return verifidForm("submit_true('"+a+"', '"+b+"');");default:return submit_true(a,b)}else return submit_local()}
function submit_true(a,b){return IfExistButton()&&("Nuevo"!=a||-1<myForm.name.indexOf("lock"))?(myForm.button.value=myForm.button.defaultValue=a,myForm.preview&&(myForm.preview.value=myForm.preview.defaultValue=b),UpdateForm=!1,lockScreen(),myForm.submit(),!0):submit_local()}
function submit_local(){try{if("JQU"==app_UI){if(myForm&&"FORM"==myForm.tagName){document.getElementById("main").innerHTML=$main;var a=document.body.querySelectorAll("script");a&&Object.keys(a).forEach(function(b){eval(a[b].innerHTML)});document.title=document.oldTitle;onLoad()}}else historyButton?historyButton=!1:(disable_pagecontainerbeforechange=!0,history.back())}catch(b){console.error(b)}return!0}
function restore_VALUE(a){setTimeout(function(){ONBEFOREUNLOAD=!1;disable_pagecontainerbeforechange=!0;if(0>a+1)history.go(a+1);else try{eval(a)}catch(b){console.error(b,a)}setTimeout(function(){ONBEFOREUNLOAD=!0;disable_pagecontainerbeforechange=!1;UpdateForm=!0},500)},100)}
function verifidForm(a){var b=$(document.querySelector(".ui-popup-active")||document.querySelector(".ui-page-active"));y=b.length?b.find("form[name^=myForm]")[0]||b.find("form")[0]||b[0]:myForm;if(y==myForm&&IfExistForm())for(b=0;b<myForm.length;b++)if(myForm[b].name&&!myForm[b].disabled&&verifidElement(myForm[b])){ESCAPE2=0;console.dir(myForm[b]);if(confirm("Los datos han sido modificados. Es posible que los cambios que implementaste no se puedan guardar."))break;return!1}ESCAPE2=1;setTimeout(function(){ESCAPE2=
0},500);try{eval(a)}catch(c){console.error(c,a)}return!0}function verifidElement(a){switch(a.type){case "radio":case "checkbox":return a.checked!=a.defaultChecked;case "select-one":return a[a.selectedIndex].value.trim()&&a[a.selectedIndex].selected!=a[a.selectedIndex].defaultSelected;case "select-multiple":for(var b=0;b<a.length;b++)if(a[b].value.trim()&&a[b].selected!=a[b].defaultSelected)return!0;return!1;case "submit":return!1;default:return a.value!=a.defaultValue}}
function fixedForm(a){for(a=0;a<myForm.length;a++)myForm[a].name&&!myForm[a].disabled&&fixedElement(myForm[a])}function fixedElement(a){switch(a.type){case "radio":case "checkbox":return a.defaultChecked=a.checked;case "select-one":return a[a.selectedIndex].defaultSelected=a[a.selectedIndex].selected;case "select-multiple":for(var b=0;b<a.length;b++)a[b].defaultSelected=a[b].selected;return!1;case "submit":return!1;default:return a.defaultValue=a.value}}
function IfExistButton(){return myForm.button&&!myForm.button.disabled}function IfExistForm(){return myForm.name&&6==myForm.name.length-myForm.name.toLowerCase().indexOf("myform")}function LoadInvent(a,b,c,d){if(!CheckLeaseTime_EXPIRATION())return!1;""==b?jQuery_confirm("","El Inventario NO Existe!<br>Debe seleccionar un codigo Valido"):($main="",d||=1,lockScreen(),CallSQL("^INV.www",d,"",a))}
function LoadCompany(a,b,c){if(!CheckLeaseTime_EXPIRATION())return!1;if(""==b)jQuery_confirm("","La Compa&#241;ia NO Existe<br>Debe colocar un codigo valido");else{try{historyMenu.forEach(function(){history.back()})}catch(d){}setTimeout(function(){lockScreen();CallSQL("^CIA.www","UpDate","",a,window.location.href)},500)}}function CheckLeaseTime_OK(){Cookies("Remove","passwd");CheckLeaseTimer||(CheckLeaseTime(),CheckLeaseTimer=setInterval("CheckLeaseTime()",1E3))}
function CheckLeaseTime(){CheckLeaseTime_EXPIRATION()?CheckLeaseTime_UNLOCK():CheckLeaseTime_LOCK()}function CheckLeaseTime_EXPIRATION(){var a=new Date;a="0"!=sii_leaseTimer?NUM(Cookies("Read",sii_fid0+"_sii_leaseTime"))-(a.getTime()-6E4*a.getTimezoneOffset()):1;return 0<a?a:!1}function CheckLeaseTime_CONTINUE(a){Cookies("Write","passwd",a);CallSQL("^LOGIN.www","RefreshLeaseTime")}
function CheckLeaseTime_LOCK(){if(!jQframeObj[frame_name]||""==jQframeObj[frame_name]){frame_name="checkCredentials";AE=document.activeElement;if("JQU"==app_UI){try{$("#main")[0].style.display="none"}catch(b){console.error(b)}jQframeObj[frame_name]=$('<div id="'+frame_name+'" title="Atencion!" style="text-align:center"><br><br>el tiempo de conexion a expirado, debe revalidar sus credenciales<p><input style="position:absolute;width:0;height:0;border:0;" ><input type="password" name="passwd" size="30" placeholder="Ingrese clave de '+
sii_login+'" style="text-align:center" readonly><input style="position:absolute;width:0;height:0;border:0;"></div>').dialog({resizable:!0,modal:!0,width:600,height:200,show:{effect:"fade",duration:400},beforeClose:function(){return!1},position:{my:"center top+200",at:"center top"}});document.getElementsByName("passwd")[0].focus()}else $(":mobile-pagecontainer").pagecontainer("getActivePage")[0].style.display="none",jQframeObj[frame_name]=$('<div data-role="popup" id="'+frame_name+'" data-theme="a" data-overlay-theme="b" data-dismissible="false"><center><div class="ui-btn ui-icon-lock ui-btn-icon-right ui-btn-b" style="text-align:left;margin: -1px -1px -1px -1px;">login</div><div data-role="main" class="ui-content"><h3>el tiempo de conexion a expirado, debe revalidar sus credenciales<p><input style="position:absolute;width:0;height:0;border:0;" data-role="none"><input type="password" name="passwd" placeholder="Ingrese clave de '+
sii_login+'" style="text-align:center" class="ui-corner-all ui-shadow" readonly><input style="position:absolute;width:0;height:0;border:0;" data-role="none"></h3></center></div></div>').popup({history:!1}).trigger("create").popup("open");var a=jQframeObj[frame_name].find("[name=passwd]");windowFocus.push(frame_name);setTimeout(function(){a[0].readOnly=!1;a[0].focus();a[0].select();a.on("blur",function(){this.focus()});a.on("change",function(){CheckLeaseTime_CONTINUE(this.value)})},300)}}
function CheckLeaseTime_UNLOCK(){if(jQframeObj[frame_name]&&""!=jQframeObj[frame_name]&&"checkCredentials"==frame_name){var a=jQframeObj[frame_name];jQframeObj[frame_name]="";a[0].querySelector("input[name=passwd]").onblur="";try{"JQU"==app_UI?(a.dialog("destroy"),$("#main")[0].style.display=""):(a.popup("destroy"),$(":mobile-pagecontainer").pagecontainer("getActivePage")[0].style.display="")}catch(b){console.error(b)}try{a.remove()}catch(b){console.error(b)}AE.focus();windowFocus.splice(windowFocus.indexOf(frame_name))}}
function lockScreen(a,b,c){try{"unlock"==a?(set_lockScreen&&(clearTimeout(set_lockScreen),set_lockScreen=0),"JQU"==app_UI?$("body").removeClass("loading"):$.mobile.loading("hide")):set_lockScreen||=setTimeout(function(){set_lockScreen=0;"JQU"==app_UI?$("body").addClass("loading"):(c||={},$.mobile.loading("show",c))},b||500)}catch(d){}}function serializeForm(){originalForm=myForm&&"myForm"==myForm.name?$(myForm).serialize():!1}
function input_list(){var a=$('*[data-role="input-list"]').not(".processed");a.length&&a.each(function(){var b=$(this);b.on({mouseover:function(c){set_tableRow("",c)},click:function(c){set_tableRow_click(c)},keydown:function(c){if(c=c.currentTarget.getAttribute("data-KEYS_"+c.key)||c.currentTarget.getAttribute("data-KEYS_Any"))try{return eval(c)}catch(d){console.error(d)}}}).addClass("processed");$tr=b.children();$tr.length&&(set_tableRow_input($tr[0]),$tr[0].parentElement.tableRow=$tr[0])})}
function set_tableRow(a,b){b&&b.preventDefault();var c=a||b.target||b;"TR"!=c.tagName&&(c=c.closest("tr"));(xtableRow=a?c.parentElement.tableRow:c.parentElement.tableRow_Light)&&set_tableRow_blur(xtableRow,a,b);(xtableRow=c)&&set_tableRow_focus(xtableRow,a,b)}function set_tableRow_blur(a,b,c){b?a.classList.remove("SELECT"):a.classList.remove("SELECT_Light")}
function set_tableRow_focus(a,b,c){if(b)return a.parentElement.tableRow=a,a.classList.add("SELECT"),a=set_tableRow_input(a),a.focus(),a;a.parentElement.tableRow_Light=a;a.classList.add("SELECT_Light")}
function set_tableRow_input(a){try{var b=a.parentElement.tableRow.querySelector("input[class=Input_Hidden_For_Focus]");b&&(b.style.display="none")}catch(f){}b=a.querySelector("input[class=Input_Hidden_For_Focus]");if(!b){b=document.createElement("input");navigator.userAgent.toUpperCase().indexOf("ANDROID")+1&&(b.type="checkbox");b.name="inputList"+(new Date).getTime();b.classList.add("Input_Hidden_For_Focus");b.addEventListener("keydown",keySelect);var c=a.cells[0],d=c.querySelector("div");d&&(c=
d);c.appendChild(b);b=c.querySelector("input[class=Input_Hidden_For_Focus]");b.onblur=function(f){set_tableRow_blur(b.closest("tr"),"onFocus",f)};b.onfocus=function(f){set_tableRow_focus(b.closest("tr"),"onFocus",f)}}b.style.left=a.closest("div").scrollLeft+5+"px";b.style.display="inline";return b}function set_tableRow_click(a){a.preventDefault();var b=a.target;"TR"!=b.tagName&&(b=b.closest("tr"));var c=b.parentElement,d=c.tableRow;d&&d==c.tableRow_Light?tableRow_Enter(a):set_tableRow(b,a)}
function tableRow_Enter(a){var b=a.target;"TR"!=b.tagName&&(b=b.closest("tr"));if(void 0!=b.dataset.onclick)try{return eval(b.dataset.onclick),set_tableRow(b,a),a.stopPropagation(),!1}catch(c){console.error(c,b.dataset.onclick)}else return"click"!=a.type?KEYS_13(1):set_tableRow(b,a),!1}
function elementSibling(a,b,c,d){d&&d.preventDefault();e=a||d.target;"TR"!=e.tagName&&(e=e.closest("tr"));for(a=e;0<c--&&null!=e;){"next"==b?e=e.nextElementSibling:"previous"==b&&(e=e.previousElementSibling);try{"TR"!=e.tagName||""==e.innerText.trim()?c++:a=e}catch(f){}}try{for(;b&&""==e.innerText.trim();)"next"==b?e=e.previousElementSibling:"previous"==b&&(e=e.nextElementSibling)}catch(f){}null!=e&&""!=e.innerText.trim()&&(a=e);set_tableRow(a,d)}
function keySelect(a){EVENT=a||event;a.key=a.key||a.keyIdentifier;a.key&&a.key.indexOf("U+")+1&&(a.key=String.fromCharCode(a.keyCode));var b=a.keyCode,c=a.target.closest("tr").parentElement.tableRow;a.ctrlKey&&(38==b?b=a.shiftKey?36:33:40==b&&(b=a.shiftKey?35:34));if("function"==typeof window.My_keySelect&&!My_keySelect(a))return!1;switch(b){case 33:return elementSibling(c,"previous",lineNum,a),!1;case 34:return elementSibling(c,"next",lineNum,a),!1;case 35:return elementSibling(c.parentElement.lastElementChild,
"next",0,a),!1;case 36:return elementSibling(c.parentElement.firstElementChild,"previous",0,a),!1;case 37:return c.closest("div").scrollLeft-=EVENT.ctrlKey||a.ctrlKey?EVENT.shitKey||a.shiftKey?1E5:500:100,!1;case 38:return elementSibling(c,"previous",1,a),!1;case 39:return c.closest("div").scrollLeft+=EVENT.ctrlKey||a.ctrlKey?EVENT.shiftKey||a.shiftKey?1E5:500:100,!1;case 40:return elementSibling(c,"next",1,a),!1;case 13:return b=c.closest("tbody").dataset.enter,a.shiftKey||""<b&&"[OFF|FALSE|0]".indexOf(b.toUpperCase())?
!0:tableRow_Enter(a);case 32:return tableRow_Enter(a);default:return!0}}function HTA(a){a=(a||"")+"";for(var b="",c,d=0;d<a.length;d++)c="0"+a.charCodeAt(d).toString(16).toUpperCase(),b+=c.substr(c.length-2,2);return b}function ATH(a){a=(a||"")+"";for(var b="",c=0;c<a.length-1;c+=2)b+=String.fromCharCode(parseInt(a.substr(c,2),16));return b}
function BIN(a,b){b=b||1;var c=0;a=parseInt(a||0);0>a&&(c=255,a+=1);for(var d="",f=0;f<b;f++)x=parseInt(a/256),d=String.fromCharCode(a-256*x+c)+d,a=x;return d}function DEC(a){a=(a||"")+"";for(var b=0,c=0;c<a.length;c++)b=256*b+a.charCodeAt(c);return b>=256**c/2?b-256**c:b}
function NUM(a,b){a=(a||"")+"";for(var c="",d=0,f;d<a.length;d++)f=a.charAt(d),"%&()*+-./0123456789<>?^|".indexOf(f)+1&&(c+=f);if(isNaN(c))try{c=eval(c)}catch(h){console.error(h,c)}c=""==c?0:parseFloat(c);return void 0!=b?(a=Math.pow(10,0<b?b:0),parseInt(c*a+.55555555555*Math.sign(c))/a):c}function CRC(a,b){b=Reflect(DEC(b),16);for(var c=0,d;c<a.length;c++)d=Reflect(a.charCodeAt(c)&255,8),b^=d<<8&65535,d=b>>8&255,b=b<<8&65535,b^=crcTable[d]&65535;return BIN(Reflect(b,16)&65535,2)}
function Reflect(a,b){for(var c=0,d=0;d<b;d++)a&1<<d&&(c|=1<<b-1-d&(1<<b)-1);return c}for(var crcTable=Array(256),i=0;256>i;i++){for(var Byte=i<<8,bit=0;8>bit;bit++)Byte=Byte&32768?Byte<<1^32773:Byte<<1;crcTable[i]=Byte&65535}
function MASK(a,b,c,d,f){var h=point=number=x=y=z=x1=x2=s=0,g="";if(x1=c.indexOf(".")+1)for(h=c.length-x1,x=x1;x<c.length;x++)-1=="#0".indexOf(c.charAt(x))&&h--;number=NUM(b,h);b=number+"";0>number&&(b=b.substr(1));(x2=b.indexOf(".")+1)?point=b.length-x2:h&&(b+=".",x2=b.length);if(h>point)for(x2||(b+="."),x=point;x<h;x++)b+="0";if(1==d||number){x=x2?x2-1:b.length;for(y=x1?x1-1:c.length;x<b.length||y<c.length;){for(;y<c.length&&(!("#0.".indexOf(z=c.charAt(y))+1)||x>=b.length);){if("B"==z||"#"==z||
"-()CR".indexOf(z)+1&&0<=number)z=" ";g+=z;y++}x<b.length&&(g="#"==c.charAt(y)&&"0000000000000000".indexOf(b.substr(x))+1?g+" ":g+b.charAt(x),x++);y++}x=x2?x2-2:b.length-1;for(y=x1?x1-2:c.length-1;0<=x||0<=y;){for(;0<=y&&(!("#0.".indexOf(z=c.charAt(y))+1)||0>x);){if("B"==z||"#"==z||"-()CR".indexOf(z)+1&&0<=number||0>x&&","==z)z=" ";if("-"==z||"("==z)for(s=0;" "==g.substr(s,1);s++);else s=0;g=g.substr(0,s)+z+g.substr(s);y--}0<=x&&(g="#"==c.charAt(y)&&"0000000000000000".indexOf(b.substr(0,x+1))+1?" "+
g:b.charAt(x)+g,x--);y--}}1!=f&&(g=g.trim());a&&(a.value=g,0>number?(void 0==a.backup_color&&(a.backup_color=a.style.color),a.style.color="red"):void 0!=a.backup_color?(a.style.color=a.backup_color,a.backup_color=void 0):a.style.color="");return g}
function CallHELP(a,b,c){a=a||"Ayuda de SINFONIX 2000 "+sii_name;b=b||"/html/sinfonix_help/"+sii_system2+"index.htm";c=c||sii_helpLink||"/html/sinfonix_help/"+sii_system2+"logo.hlp.htm";var d=window.open("","Help","screenX=150, screenY=50, width=650, height=450, resizable");d.document.open();d.document.write("<html>");d.document.write("<head>");d.document.write("<title>"+a+"</title>");d.document.write("</head>");d.document.write('<frameset rows="32,100%" frameborder="YES" border="0">');d.document.write('  <frame name="MenuBar" src="/html/menubarHelp.htm"');
d.document.write('         marginwidth="0" frameborder="0" scrolling="NO">');d.document.write('<frameset cols="205,*">');d.document.write('  <frame name="Index" src="'+b+'"');d.document.write('         marginwidth="2" frameborder="10"  scrolling="YES">');d.document.write('  <frame name="Link" src="'+c+'"');d.document.write('         marginwidth="10" frameborder="10" scrolling="YES">');d.document.write("</frameset>");d.document.write("    <noframes>");d.document.write('    <body bgcolor="#FFFFFF">');
d.document.write("    <p>Lo siento, pero tu navegador NO tiene la capacidad de ");d.document.write("    visualizar frames.</p>");d.document.write("    </body>");d.document.write("    </noframes>");d.document.write("</frameset>");d.document.write("</html>");d.focus()}
function Cookies(a,b,c,d,f){switch(a){case "Read":return d="; "+document.cookie+"; ",a="",f=d.indexOf("; "+b+"=")+b.length+3,f>=b.length+3&&(a=d.substring(f,d.indexOf("; ",f))),decodeURIComponent(a);case "Write":return a=b+"="+encodeURIComponent(c),d&&!f&&(f=new Date,f.setTime(f.getTime()+864E5*d)),f&&(a+="; expires="+f.toGMTString()),document.cookie=a+"; SameSite=Lax;",decodeURIComponent(a);case "Remove":return a=b+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC",document.cookie=a+"; SameSite=Lax;",decodeURIComponent(a);
default:alert("nulluse: Cookies(action, name[, value[, days[, expires]]])\n     where: action is 'Read', 'Write', 'Remove'\n            name is Name of Cookies\n            value is data to Write\n            days is number of days to expires a Cookies.\n          & expires is date to expires a Cookies.\n")}}function photo(a,b){alert("Correjir programa para usar photoZoom");photoZoom(a,b)}
function photoZoom(a,b){var c=$("#"+a)[0];a=$("#"+a).clone();var d=a.data("file");b+="Haz clic en la imagen para ";b=d?b+"Cambiarla":b+"Cerrarla";a.attr("onclick","return");a.dialog({title:b,height:c.naturalHeight,width:c.naturalWidth,modal:!0,show:{effect:"fade",duration:400},position:{my:"center top",at:"center top"}}).on("click",function(){d&&$(d).click();$(this).dialog("destroy")})}
function photoChange(a,b){var c=b.target,d=$(a);if("DELETE"==b||c.id.indexOf("_delete")+1)d.fadeIn("fast").attr("src",d.data("defaulticon")||iconGeneric),$("#"+c.id.split("_delete")[0]).val("");else switch(c.files[0].type){case "application/pdf":d.fadeIn("fast").attr("src","/images/file-pdf.png");break;case "application/vnd.ms-excel":case "application/vnd.oasis.opendocument.spreadsheet":case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":d.fadeIn("fast").attr("src","/images/file-xls.png");
break;case "application/msword":d.fadeIn("fast").attr("src","/images/file-doc.png");break;case "application/zip":case "application/x-rar":d.fadeIn("fast").attr("src","/images/file-zip.png");break;case "text/csv":case "text/plain":case "text/html":d.fadeIn("fast").attr("src","/images/file-txt.png");break;case "audio/mp3":d.fadeIn("fast").attr("src","/images/file-mp3.png");break;default:if(c.files[0].type.indexOf("image")+1){a=new FileReader;a.onload=function(f){void 0==d[0].saveSrc&&(d[0].saveSrc=
d[0].src);f.target.result&&d.fadeIn("fast").attr("src",f.target.result);$("#"+c.id+"_delete").val("")};try{a.readAsDataURL(c.files[0])}catch(f){console.error(f),d.fadeIn("fast").attr("src",d[0].saveSrc)}}else d.fadeIn("fast").attr("src","/images/file-unknown.png")}}
function selectList(a,b,c,d,f){"object"==typeof f&&a&&void 0==a.db&&optionAdd(a,f);if(void 0!=a){var h={},g={},l=count=v=o=0;for(k in b)if(x=b[k])h[HTA(x.trim())]="ok",v++;for(k in c)if(x=c[k])g[HTA(x.trim())]="ok",o++;for(var k=0;k<a.length;k++)!o||a.options[k].value in g?(a.options[k].disabled="",a.options[k].style.display="",count++,a.options[k].value in h?(a.options[k].selected=!0,l=k):l||v||1!=a.options[k].selected||1==f?a.options[k].selected=!1:l=k):(a.options[k].disabled="true",a.options[k].style.display=
"none",a.options[k].selected=!1);1==d&&(a.options[l].defaultSelected=a.options[l].selected,a.initValue=a.selectedIndex);if("JQM"==app_UI)try{$(a).selectmenu("refresh",!0)}catch(m){}return l}}function optionAdd(a,b){a.db="ok";var c=a.innerHTML;for(i in b){var d=b[i].key||i;if(!(c.indexOf('value="'+d+'"')+1)){var f=document.createElement("option");f.value=d;f.innerHTML=b[i].label;a.add(f)}}}
function PressEnter(a){if(a.initValue&&(a.type.toLowerCase().indexOf("select")+1?a.selectedIndex:a.value)!=a.initValue)return!0;if(EVENT&&"keydown"==EVENT.type){var b=EVENT.target,c=document.all?EVENT.keyCode:EVENT.which;if(!EVENT.shiftKey&&13==c&&b.name==a.name)return!0}return!1}blurElement=focusElement="";function select_activeElement(){focusElement=document.activeElement}
function JS(a,b,c){"focus"==b&&blurElement&&(a&&selectClass(blurElement,c)==selectClass(a,c)||JS(blurElement,"blur",c));blurElement="";if(a&&(Elm="focus"==b?focusElement:document.activeElement,selectClass(Elm,c)!=selectClass(a,c))){try{js=eval("document.getElementById( '"+selectClass(a,c)+"' ).on"+b)+""}catch(d){}z=js.indexOf("{\n");z+1&&(js=js.substr(z+2),z=js.indexOf("\n}"),z+1&&(js=js.substr(0,z)));z=js.toLowerCase().indexOf("javascript:");z+1&&(js=js.substr(z+11));try{return eval(js)}catch(d){}}}
function selectClass(a,b){z=a.className+" ";x=z.indexOf(b);return x+1?z.substr(x,z.indexOf(" ")):""}function progressBar(a,b,c,d){a=$('<div id="modalProgressBar"><div id="message" style="color:black">'+(a||"En proceso...")+'</div><br><br><svg id="progressbar"></svg></div>');a.modal({escapeClose:b,clickClose:c,showClose:d});b=a.find("#progressbar").Progress({width:a.width(),height:40,barColor:"#5E9DE6",animate:!1});return{frame:a,progress:b}}
function progressBar_close(a){close_progress_bar=!1;pbar="";$.modal.close()}function CallSQLTBL(a,b,c,d,f){"object"==typeof b&&(b=b.options?ATH((b.options[b.selectedIndex]||"").value):b.value);c=c||"LoadTBL";d=d||"record";f=f||a.substr(0,2);EVAR=a;CallSQL("^TBLM.sql "+EVAR,d,b,f+"?? "+EVAR+" "+c,"record")}function LoadTBL(a){eval(EVAR+" = ATH(record)")}
function send_eMail(){if(!jQframeObj[frame_name]||""==jQframeObj[frame_name]||"^LOGIN.www"==sql){sii_To.toUpperCase().indexOf("$PRN_")||(sii_To="");sii_Cc.toUpperCase().indexOf("$PRN_")||(sii_Cc="");sii_Bcc.toUpperCase().indexOf("$PRN_")||(sii_Bcc="");sii_Subject.toUpperCase().indexOf("$PRN_")||(sii_Subject="");sii_Message.toUpperCase().indexOf("$PRN_")||(sii_Message="");sii_Flag.toUpperCase().indexOf("$PRN_")||(sii_Flag="");var a=document.body.parentNode.innerHTML.split('\nsii_leaseTimer    = "'),
b=document.title;for(i in a)0!=i&&(a[i]='0"; //'+a[i]);a=a.join('\nsii_leaseTimer    = "').split("page-break-before:always;").join("");-1==sii_Flag.toUpperCase().indexOf("CONVERT=")&&(sii_Flag+=" Convert=.PDF ");jQframeObj.SENDMAIL?jQframeObj.SENDMAIL.dialog("open"):(WIDTH=635,HEIGHT=405,jQframeObj.SENDMAIL=$('        <div id="SENDMAIL" title="Envio de Correo Electronico" style="border: 0px; width:'+WIDTH+"px; height:"+HEIGHT+'px; overflow: hidden;">         <form action="/cgi-bin/sinfonix.pl?'+sii_system+
' ^EMAIL" method="POST" enctype="multipart/form-data" name="myForm_Mail" target="connect9">          <table style="width=100%;">           <tr><td style="width:60px"                  ><input name="prn_To"      style="width:100%" value="'+sii_To+'" placeholder="Para"   required></td></tr>           <tr><td><input name="prn_Cc"      style="width:100%" value="'+sii_Cc+'" placeholder="Copia"          ></td></tr>           <tr><td><input name="prn_Bcc"     style="width:100%" value="'+sii_Bcc+'" placeholder="Copia Oculta"   ></td></tr>           <tr><td><input name="prn_Subject" style="width:100%" value="'+
sii_Subject+'" placeholder="Asunto" required></td></tr>           <tr><td><div     id="prn_editor"  style="width:100%">'+ATH(sii_Message)+'</div><br></td></tr>           <tr><td><input name="prn_Acepta"  style="width:100%" value="E n v i a r   C o r r e o" type="submit" onclick="return send_eMail_continue(event);"></td></tr>          </table>          <div style="display:none">           <input type="hidden" name="prn_Message" required>           <input type="hidden" name="prn_Attachments">           <input type="hidden" name="prn_Flag"  value="'+
sii_Flag+'">           <input type="hidden" name="prn_Html"  value="'+HTA(a)+'">           <input type="hidden" name="prn_Title" value="'+b+'">          </div>         </form>        </div>     ').dialog({modal:!0,width:WIDTH-1,height:HEIGHT+39,show:{effect:"fade",duration:400},create:function(c){$("#prn_editor").summernote({placeholder:"Mensaje...",width:608,height:195,minHeight:null,maxHeight:null,dialogsInBody:!0,toolbar:[["font",["fontname","fontsize","color","bold"]],["paragraph",["paragraph",
"table"]],["Insert",["picture","video"]],["Misc",["fullscreen","codeview","help"]]]})},beforeClose:function(c){c.stopPropagation();win=window.frames[this.id];windowFocus.splice(windowFocus.indexOf(win.jQname))}}));windowFocus.push("SENDMAIL")}}
function send_eMail_continue(a){a=a.target.closest("form");var b=document.createElement("div"),c="",d="";b.innerHTML=a.querySelector("[name=prn_Message]").value=$("#prn_editor").summernote("code");var f=a.querySelector("[name=prn_To]");f.value=email_trim(f.value);c+=validated_eMail("Para",f.value);f=a.querySelector("[name=prn_Cc]");f.value=email_trim(f.value);c+=validated_eMail("Copia",f.value);f=a.querySelector("[name=prn_Bcc]");f.value=email_trim(f.value);c+=validated_eMail("Copia (Oculta)",f.value);
a.querySelector("[name=prn_To]").value.trim()||(d+='Debe colocar al menos un Email "Para" Valido!\n');a.querySelector("[name=prn_Subject]").value.trim()||(d+='Debe colocar un "Asunto" Valido!\n');b.innerText.trim()||(c+='Debe colocar un "Mensaje" Valido!\n');if(c)return alert(c),!1;d||lockScreen();return!0}
function validated_eMail(a,b){var c=/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,4})+$/,d="";b=email_trim(b).split(" ");b.forEach(function(f){f&&!c.test(f)&&(d+='Uno de los Email "'+a+'"('+f+") no es Valido!\n")});return d}function email_trim(a){return a.split(";").join(" ").split(",").join(" ").replace(/\s\s+/g," ").trim()}function toGraphX(a){toGraphAxis("X",a.target,a.target.closest("tr").querySelectorAll("td"));return!1}
function toGraphY(a){toGraphAxis("Y",a.target,a.target.closest("table").querySelectorAll("tr > td"+(a.target.dataset.level?".level"+a.target.dataset.level:"")+":nth-child("+(1+a.target.cellIndex)+")"));return!1}
function toGraphAxis(a,b,c){var d=b.closest("table"),f=NUM(b.cellIndex)+1E3*NUM(b.parentNode.rowIndex),h=[];d.dataset.axis!=a&&toGraphInit(b);d.dataset.axis=a;c.forEach(function(g){g.classList.contains("toGraph")?g.classList.remove("toGraph"):(g.classList.add("toGraph"),h.push(NUM(g.innerText)||0))});h.length?(toGraphData[f]={label:b.innerText.trim(),data:h},toGraph(b)):delete toGraphData[f]}
function toGraph(a){clearTimeout(CTRLKEY);if(EVENT&&EVENT.ctrlKey)return CTRLKEY=setTimeout(function(){toGraph(a)},100),!1;var b=a.closest("table"),c=b.dataset.axis;if(b.querySelectorAll("td.toGraph").length){var d={title:document.querySelectorAll(".toGraphTitle")[0].innerText.trim()+" "+b.querySelectorAll(".toGraphTitle.level"+a.dataset.level)[0].innerText.trim(),type:"Bar"};b=b.querySelectorAll(".toGraph"+("X"==c?"Y":"X")+".level"+a.dataset.level);d.labels=[];for(c=0;c<b.length;c++)d.labels.push(b[c].innerText.trim());
d.datasets=[];for(var f in toGraphData)d.datasets.push(toGraphData[f]);CallPGM("^GRAPH.www Chart="+HTA(JSON.stringify(d)))}toGraphInit(a)}function toGraphInit(a){a.closest("table").querySelectorAll("td.toGraph").forEach(function(b){b.classList.remove("toGraph")});toGraphData={}}
function DateToString_ES(a,b){b=b||"";var c="Domingo Lunes Martes Miercoles Jueves Viernes Sabado".split(" ");var d="Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre".split(" ");a=a?new Date(a):"Invalid Date";if("Invalid Date"!=a){var f=1<b.toUpperCase().split("MONTH_LONG").length;var h=1<b.toUpperCase().split("DAY_LONG").length;Short_Date=1<b.toUpperCase().split("SHORT_DATE").length;b=(Numeric=1<b.toUpperCase().split("NUMERIC").length)?MASK("",a.getMonth()+
1,"00",1):d[a.getMonth()];Numeric||(b=f?"de "+b+" del":b.substr(0,3));c=Numeric?MASK("",a.getDay(),"00",1):c[a.getDay()];Numeric||h||(c=c.substr(0,3));a=a.toString().split(" ");a[0]=c;a[1]=a[2];a[2]=b;Short_Date?(h=a[4].split(":"),a=a[0]+", "+a[1]+" "+a[2]+" "+a[3]+" a las "+h[0]+":"+h[1]+":"+h[2].split(" ")[0]):a=a.join(" ")}return a}
function delayUpLoadPage(a){if(0!=location.href.toUpperCase().indexOf("HTTP")){a=(new Date).getTime()+a;for(var b=new XMLHttpRequest;(new Date).getTime()<a;)b.open("GET",location.href,!0),b.send()}}
function setAutocomplete(a){a=a.target||a;"autocomplete"==a.name&&localStorage.setItem("autocomplete",a.defaultChecked=a.checked);a.checked?setTimeout(function(){autocomplete.forEach(function(b){b.defaultValue=b.value})},3E3):(autocomplete.forEach(function(b){b.oldReadOnly=b.readOnly;b.readOnly=!0;b.value=b.defaultValue}),setTimeout(function(){autocomplete.forEach(function(b){b.readOnly=b.oldReadOnly;b.value=b.defaultValue})},1E3))}
function sii_required(a,b,c){try{if("function"==typeof eval(a))sii_required_callBack(c);else throw"funcion no definida";}catch(d){"./".includes(b.substr(0,1))||(a=sii_path_htm_name.split("/"),1<a.length&&(a[a.length-1]="",b=".."+a.join("/")+b)),b.includes(sii_version)||(b+=(-1!=b.indexOf("?")?"%20":"?")+sii_version),$.ajax({url:b,dataType:"script",cache:!0}).always(function(f,h,g){sii_required_callBack(c)})}}function sii_required_callBack(a){a&&("function"==typeof a?a():eval(a))}
function STDIO_ready(a,b,c,d){STDIO_JavaScript=a||"";STDIO_message=b||"";STDIO_error=c||"";STDIO_Title=d||"";STDIO_wp=window.parent;STDIO_onLoad()}
function STDIO_onLoad(){console.info("error:",STDIO_error,"\nmessage:",STDIO_message,"\nJavaScript:",STDIO_JavaScript);try{STDIO_wp.CheckLeaseTime_OK()}catch(a){}try{STDIO_wp.jQuery.modal.close()}catch(a){}try{STDIO_wp.lockScreen("unlock")}catch(a){}STDIO_wp.setTimeout(function(){try{STDIO_wp.UpdateForm=!0}catch(a){}},500);STDIO_Title||=STDIO_error?"Alerta!":"Atenci\u00f3n!";if("JQU"==STDIO_wp.app_UI)STDIO_error?(alert(STDIO_message.split("<BR>").join("\n")+"\n\n"+STDIO_error.split("<BR>").join("\n")),
"connect9"==window.name?goBack(-1):$main?($("#main").html($main),onLoad()):(window.document.referrer==window.parent.location.href&&setTimeout(function(){KEYS_27(KEYS_27("close"))},500),goBack(-1))):(STDIO_message&&"connect9"!=window.name&&alert(STDIO_message.split("<BR>").join("\n")),STDIO_execute(),setTimeout(function(){"connect9"==window.name&&goBack(-1)},500));else if(STDIO_error)alert(STDIO_message.split("<BR>").join("\n")+"\n\n"+STDIO_error.split("<BR>").join("\n")),"connect9"==window.name&&
goBack(-1);else if(STDIO_message)try{STDIO_wp.jQuery_confirm(STDIO_Title,STDIO_message,"","","","",function(){STDIO_execute()})}catch(a){alert(STDIO_message.split("<BR>").join("\n")),STDIO_execute()}else STDIO_execute()}
function STDIO_execute(){STDIO_wp.ONBEFOREUNLOAD=!1;STDIO_wp.disable_pagecontainerbeforechange=!0;STDIO_wp.setTimeout(function(){ONBEFOREUNLOAD=!0;disable_pagecontainerbeforechange=!1;UpdateForm=!0},500);try{STDIO_wp.fixedForm(),eval(STDIO_JavaScript)}catch(a){console.error(a,STDIO_JavaScript)}}function goBack(a){try{STDIO_wp.restore_VALUE(0>a?a:"undefined"==typeof a?-2:a)}catch(b){}history.go(-1)}
function urlBase64ToUint8Array(a){var b="=".repeat((4-a.length%4)%4);a=(a+b).replace(/\-/g,"+").replace(/_/g,"/");a=window.atob(a);b=new Uint8Array(a.length);for(let c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}function GeoLocation(){sii_GPS_timestamp=sii_GPS_timestamp2=(new Date).getTime();watchID=navigator.geolocation.watchPosition(GPS_success,GPS_error,{maximumAge:1E4,timeout:6E5,enableHighAccuracy:!0})}
function GPS_success(a){zGPS={coords:{accuracy:a.coords.accuracy,altitude:a.coords.altitude,altitudeA:a.coords.altitudeAccuracy,heading:a.coords.heading,latitude:a.coords.latitude,longitude:a.coords.longitude,speed:a.coords.speed},timestamp:a.timestamp,timestampUp:a.timestamp};localStorage.setItem("GPS",JSON.stringify(zGPS));if("undefined"!=typeof ol)if(console.log("GPS",a),a=JSON.parse(localStorage.getItem("sii_GPS"))||[],a.length){var b=ol.proj.transform([a[0].coords.longitude,a[0].coords.latitude],
"EPSG:4326","EPSG:3857"),c=ol.proj.transform([zGPS.coords.longitude,zGPS.coords.latitude],"EPSG:4326","EPSG:3857");b=new ol.geom.LineString([b,c]);b=Math.round(100*b.getLength())/100;25>b?(a[0].timestampUp=zGPS.timestampUp,a=[a[0]]):a.push(zGPS);localStorage.setItem("sii_GPS",JSON.stringify(a));console.log(b,zGPS.timestamp-sii_GPS_timestamp);18E4<zGPS.timestamp-sii_GPS_timestamp&&(b=a[0],1<a.length?(a.splice(0,1),localStorage.setItem("sii_GPS",JSON.stringify(a)),sii_GPS_timestamp=a[0].timestamp):
sii_GPS_timestamp=zGPS.timestamp,GPS_update(b))}else a.push(zGPS),localStorage.setItem("sii_GPS",JSON.stringify(a)),GPS_update(zGPS)}function GPS_error(a){console.error(a)}
function GPS_update(a){var b=JSON.parse(localStorage.getItem("sii_GPS_DB2"))||[],c=JSON.parse(localStorage.getItem("sii_GPS_DB"))||[];var d=b.length-1;-1<d&&b[d].coords.longitude==a.coords.longitude&&b[d].coords.latitude==a.coords.latitude?b[d]=a:b.push(a);localStorage.setItem("sii_GPS_DB2",JSON.stringify(b));c.length&&6E5>b[b.length-1].timestamp-sii_GPS_timestamp2||(sii_GPS_timestamp2=b[b.length-1].timestamp,GPS_update_Remote())}
function GPS_update_Remote(){var a=JSON.parse(localStorage.getItem("sii_GPS_DB2"))||[],b=JSON.parse(localStorage.getItem("sii_GPS_DB"))||[],c=Cookies("Read","pushMsg")||"",d;c=setForm("subscription",c);var f=a.length;for(d=0;d<f;d++)c+=setForm("accuracy"+d,a[d].coords.accuracy),c+=setForm("altitude"+d,a[d].coords.altitude),c+=setForm("altitudeA"+d,a[d].coords.altitudeA),c+=setForm("heading"+d,a[d].coords.heading),c+=setForm("latitude"+d,a[d].coords.latitude),c+=setForm("longitude"+d,a[d].coords.longitude),
c+=setForm("speed"+d,a[d].coords.speed),c+=setForm("timestamp"+d,a[d].timestamp),c+=setForm("timestampUp"+d,a[d].timestampUp);console.log(c.split("&").join("\n"));fetch("/cgi-bin/sinfonix_sql.pl?^SW.www GeoLocation",{method:"post",headers:{"Content-type":"application/x-www-form-urlencode","Content-length":c.length},body:c}).then(function(){d=b.length-1;for(-1<d&&b[d].coords.longitude==a[0].coords.longitude&&b[d].coords.latitude==a[0].coords.latitude&&b.splice(d);!b.length||1<a.length;)b.push(a[0]),
1<a.length&&a.splice(0,1);localStorage.setItem("sii_GPS_DB2",JSON.stringify(a));for(var h=(new Date).getTime()-5184E6;3E3<b.length||b[0].timestamp<h;)b.splice(0,1);localStorage.setItem("sii_GPS_DB",JSON.stringify(b))})}function setForm(a,b){return a+"="+escape(b||"")+"&"}
function Haversine(a,b){var c=a[1];const d=b[1],f=(d-c)*Math.PI/180;a=(b[0]-a[0])*Math.PI/180;c=Math.sin(f/2)*Math.sin(f/2)+Math.sin(a/2)*Math.sin(a/2)*Math.cos(c*Math.PI/180)*Math.cos(d*Math.PI/180);return 12742E3*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))}function coord2tile(a,b){b=2**b;const c=a[1]*Math.PI/180;a=parseInt((a[0]+180)/360*b);b=parseInt((1-Math.log(Math.tan(c)+1/Math.cos(c))/Math.PI)/2*b);return[a,b]}
function tile2coord(a,b){b=2**b;return[a[0]/b*360-180,Math.atan(Math.sinh(Math.PI*(1-2*a[1]/b)))/Math.PI*180]}function __DELETE__NoEdit(a){jQuery_confirm("","Este campo no puede ser editado");a.value=a.defaultValue}
function __DELETE__MyAddItem(a,b,c,d,f){var h=document.createElement("div");h.innerHTML=b;b=h.innerHTML;c=c||"";f=f||"";h="";classNoExec_enabled=!0;d&&eval(d)&&(c="NoExec();",h="jsdomenuitem_noexec",classNoExec_enabled=!1);a.addMenuItem(new menuItem(b,f,c,classNoExec_enabled,h));f&&eval("Menu.items."+f+".setSubMenu("+f+");")}
function __DELETE__set_COLS(a,b){a=1<a?a:1;b=b.target.closest("table");var c=b.querySelector("tbody").querySelectorAll("tr")[a-1];if(c.querySelectorAll("td")[0].innerText){Old_Obj&&Old_Obj.classList.remove("SELECT");c.classList.add("SELECT");var d=b.querySelector("input");if(!d){d=document.createElement("input");d.name="input-list";d.addEventListener("keydown",keySelect);d.classList.add("Input_Hidden_For_Focus");var f=c.querySelectorAll("td")[0],h=f.querySelector("div");h&&(f=h);f.appendChild(d);
d=b.querySelector("input")}setTimeout(function(){d.focus()},10);Old_Obj=c;COLS=a}}function ODef(a){html=ODef1(a,"");console.log(html);return html}function ODef1(a,b){var c="",d="";for(c in a)a[c]&&(d="object"==typeof a[c]?d+ODef1(a[c],b+" "):d+(b+c+": "+a[c]+"\n"));return d}
function ejemplos_de_cadenas_y_objectos(){x=[{code:"01"},{code:"02"},{code:"03"}];y={a:{code:"01"},b:{code:"02"},c:{code:"03"}};z=[{a:{code:"01"},b:{code:"02"},c:{code:"03"}},{a:{code:"01"},b:{code:"02"},c:{code:"03"}},{a:{code:"01"},b:{code:"02"},c:{code:"03"}}];alert(x[0].code+"-"+x[1].code+"-"+x[2].code);alert(y.a.code+"-"+y.b.code+"-"+y.c.code);alert(y.a.code+"-"+y.b.code+"-"+y.c.code);alert(z[0].a.code+"-"+z[0].b.code+"-"+z[0].c.code);alert(z[0].a.code+"-"+z[1].b.code+"-"+z[2].c.code)};
